services:
  - name: zakerny-bot
    ports:
      - port: 8000
        protocol: HTTP
    env:
      - key: TOKEN
        value: your_discord_bot_token_here
    regions:
      - fra
    scalings:
      min: 1
      max: 1
    docker:
      image: koyeb/zakerny-bot
